from .hempdawg_black_image import NODE_CLASS_MAPPINGS as _M1, NODE_DISPLAY_NAME_MAPPINGS as _D1
from .hempdawg_mask_overlay import NODE_CLASS_MAPPINGS as _M2, NODE_DISPLAY_NAME_MAPPINGS as _D2
from .hempdawg_video_resize32 import NODE_CLASS_MAPPINGS as _M3, NODE_DISPLAY_NAME_MAPPINGS as _D3
from .hempdawg_alpha_video_save import NODE_CLASS_MAPPINGS as _M4, NODE_DISPLAY_NAME_MAPPINGS as _D4

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(_M1)
NODE_CLASS_MAPPINGS.update(_M2)
NODE_CLASS_MAPPINGS.update(_M3)
NODE_CLASS_MAPPINGS.update(_M4)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_D1)
NODE_DISPLAY_NAME_MAPPINGS.update(_D2)
NODE_DISPLAY_NAME_MAPPINGS.update(_D3)
NODE_DISPLAY_NAME_MAPPINGS.update(_D4)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
